# Generated by Django 5.2.6 on 2025-09-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_rename_category_menuitem_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('title', 'category')},
        ),
    ]
